server:
  port: 8181
spring:
  application:
    name: payment-service
  cloud:
    stream:
      function:
        definition: orderCreatedEventProcessor;paymentEventSubscriber;orderPaidEventPublisher;
      bindings:
        orderCreatedEventProcessor-in-0:
          destination: orders
        orderCreatedEventProcessor-out-0:
          destination: statuses
        paymentEventSubscriber-in-0:
          destination: statuses
        paymentEventSubscriber-out-0:
          destination: paid_orders

  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5434/payment_db}
    username: ${DATABASE_USER:postgre_user}
    password: ${DATABASE_PASSWORD:postgre_secret_password}
    driver-class-name: org.postgresql.Driver
    maximum-pool-size: 100
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
#    Set this, if you run services with docker
#    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
    metrics:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    enabled: true

gateway:
  uri: http://localhost:9090