version: '3.0'
services:
  discovery:
    image: delivery/discovery:0.0.1-SNAPSHOT
    ports:
      - "8761:8761"
    restart: always

  auth-service:
    image: delivery/auth-service:0.0.1-SNAPSHOT
    ports:
      - "8083:8083"
    environment:
      - CONFIG_URI=http://discovery:8761
      - EUREKA_URI=http://discovery:8761/eureka
      - DATABASE_URL=jdbc:postgresql://psql:5432/auth_user_db
      - DATABASE_USER=postgre_user
      - DATABASE_PASSWORD=postgre_secret_password
    restart: always
    depends_on:
      - discovery

  order-service:
    image: delivery/order:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - CONFIG_URI=http://discovery:8761
      - EUREKA_URI=http://discovery:8761/eureka
      - DATABASE_URL=jdbc:postgresql://psql:5432/order_db
      - DATABASE_USER=postgre_user
      - DATABASE_PASSWORD=postgre_secret_password
    restart: always
    depends_on:
      - discovery

  payment-service:
    image: delivery/payment:0.0.1-SNAPSHOT
    ports:
      - "8181:8181"
    environment:
      - CONFIG_URI=http://discovery:8761
      - EUREKA_URI=http://discovery:8761/eureka
      - DATABASE_URL=jdbc:postgresql://psql:5432/payment_db
      - DATABASE_USER=postgre_user
      - DATABASE_PASSWORD=postgre_secret_password
    restart: always
    depends_on:
      - discovery

  inventory-service:
    image: delivery/inventory:0.0.1-SNAPSHOT
    ports:
      - "8282:8282"
    environment:
      - CONFIG_URI=http://discovery:8761
      - EUREKA_URI=http://discovery:8761/eureka
      - DATABASE_URL=jdbc:postgresql://psql:5432/inventory_db
      - DATABASE_USER=postgre_user
      - DATABASE_PASSWORD=postgre_secret_password
    restart: always
    depends_on:
      - discovery

  delivery-service:
    image: delivery/deliveryservice:0.0.1-SNAPSHOT
    ports:
      - "8383:8383"
    environment:
      - CONFIG_URI=http://discovery:8761
      - EUREKA_URI=http://discovery:8761/eureka
      - DATABASE_URL=jdbc:postgresql://psql:5432/delivery_db
      - DATABASE_USER=postgre_user
      - DATABASE_PASSWORD=postgre_secret_password
    restart: always
    depends_on:
      - discovery

  gateway:
    image: delivery/gateway:0.0.1-SNAPSHOT
    ports:
      - "9090:9090"
    environment:
      - CONFIG_URI=http://discovery:8761
      - EUREKA_URI=http://discovery:8761/eureka
    restart: always
    depends_on:
      - discovery
      - auth-service
      - order-service
      - payment-service
      - inventory-service
      - delivery-service
