server:
  port: 8761

spring:
  application:
    name: discovery
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:/config/
            - file:./config/

eureka:
  dashboard:
    path: /dashboard/
    enabled: true
  client:
    fetchRegistry: false
    registerWithEureka: false
    service-url:
      default-zone: http://localhost:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0

# could be used for debugging
#logging:
#  level:
#    org:
#      springframework: TRACE
